name: Spplice Package
on: [push]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # install dependencies
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vpk
      # create package
      - name: Build package
        run: bash run package
      # publish artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Spplice Package (unzip first)
          path: p2ghostrunner.sppkg
      # prepare website root
      - name: Preparing website root
        shell: bash
        run: |
          mkdir pages
          mv p2ghostrunner.tar.xz pages/
      # push website
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
